### ISSUE TITLE
sourmash v2 breaks stuff

### ISSUE THREAD

**Issue by phiweger** [viehwegerlib/zoo#116]
https://github.com/dib-lab/sourmash/commit/564f89d319e899fe5220c9644d7984e1b1f9053f

update Estimators class to MinHash

**Comment by luizirber** [comment]
There might be extra breakage if https://github.com/dib-lab/sourmash/pull/164 is merged (still discussing it), but overall do you think these changes clarify the API and make it easier to use?

**Comment by phiweger** [comment]
Definitely, and as it turns out I only had to change a tiny amount of code, mainly connected to the Estimators class, which I thought was an odd name anyway. So yeah, IMO the v2 sourmash API changes are an improvement.
