### ISSUE TITLE
some changes to CLI

### ISSUE THREAD

**Issue by flomock** [viehwegerlib/zoo#131]
- open help also with `-h`
- write examples for all parameters which need input
e.g. `zoo init --client 'localhost:28001' --db testdb --cell InfluenzaPA test.json`
-> couldn't find `--client` in the examples
- add autocomplete function.
e.g. `zoo init --cl` (pressing tabulator) leads to `zoo init --client`

**Comment by phiweger** [comment]
how is autocomplete achieved? are there tools for that?

**Comment by phiweger** [comment]
+1 for the examples, they are still very "rough"
